/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ar.ais.views.panels.sale;

import com.ar.ais.enums.Status;
import com.ar.ais.models.EntityBeans.Summary;
import com.ar.ais.models.EntityBeans.WorkingSchedule;
import com.ar.ais.models.Response;
import com.ar.ais.report.ReportController;
import com.ar.ais.utililty.Global;
import com.ar.ais.views.dialogs.AddCashDialog;
import com.ar.ais.views.dialogs.AddCrDialog;
import com.ar.ais.views.dialogs.AddDayDialog;
import com.ar.ais.views.dialogs.AddSummaryDialog;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Adeel rana
 */
public class SummariesPanel extends javax.swing.JPanel {

    DefaultTableModel dtmDays;
    DefaultTableModel dtmSumm;
    JPanel mainPanel;

    /**
     * Creates new form UsersPanel
     *
     * @param mainPanel
     */
    public SummariesPanel(JPanel mainPanel) {
        this.mainPanel = mainPanel;
        initComponents();
        Global.setLookNFeel(jTableDays);
        Global.setLookNFeel(jTableSumm);
        addWSDataToTable();
    }

    public SummariesPanel() {
        initComponents();
        addWSDataToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDays = new com.ar.ais.components.render.CustomTable(true);
        ;
        jButtonAddSum = new javax.swing.JButton();
        jButtonViemInvoices = new javax.swing.JButton();
        jButtonEditSum = new javax.swing.JButton();
        jButtonAddCr = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSumm = new com.ar.ais.components.render.CustomTable(true);
        jButtonAddWS = new javax.swing.JButton();
        jButtonCloseWS = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonCash = new javax.swing.JButton();
        jButtonReturn = new javax.swing.JButton();
        jButtonEditSum1 = new javax.swing.JButton();
        jButtonEditSum2 = new javax.swing.JButton();
        jButtonEditSum3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Army Expanded", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Stock In Invoices");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jTableDays.setBackground(new java.awt.Color(178, 178, 178));
        jTableDays.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableDays.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableDays.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Date", "Day", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDays.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDaysMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDays);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );

        jButtonAddSum.setBackground(new java.awt.Color(51, 51, 51));
        jButtonAddSum.setText("Add New Summary");
        jButtonAddSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddSumActionPerformed(evt);
            }
        });

        jButtonViemInvoices.setBackground(new java.awt.Color(51, 51, 51));
        jButtonViemInvoices.setText("Invoices");
        jButtonViemInvoices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViemInvoicesActionPerformed(evt);
            }
        });

        jButtonEditSum.setBackground(new java.awt.Color(51, 51, 51));
        jButtonEditSum.setText("Lock Summary");
        jButtonEditSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditSumActionPerformed(evt);
            }
        });

        jButtonAddCr.setBackground(new java.awt.Color(51, 51, 51));
        jButtonAddCr.setText("Add Credit");
        jButtonAddCr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCrActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jTableSumm.setBackground(new java.awt.Color(178, 178, 178));
        jTableSumm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableSumm.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableSumm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Date", "Summary", "Booker", "Route", "Amount", "Cash", "Credit", "Balance", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSumm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSummMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableSumm);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jScrollPane2)
                .addGap(3, 3, 3))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );

        jButtonAddWS.setBackground(new java.awt.Color(51, 51, 51));
        jButtonAddWS.setText("Add New Working Schedule");
        jButtonAddWS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddWSActionPerformed(evt);
            }
        });

        jButtonCloseWS.setBackground(new java.awt.Color(51, 51, 51));
        jButtonCloseWS.setText("Close Selected");
        jButtonCloseWS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseWSActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Working Schedules");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Summaries");

        jButtonCash.setBackground(new java.awt.Color(51, 51, 51));
        jButtonCash.setText("Add Cash");
        jButtonCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCashActionPerformed(evt);
            }
        });

        jButtonReturn.setBackground(new java.awt.Color(51, 51, 51));
        jButtonReturn.setText("Add Return");
        jButtonReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReturnActionPerformed(evt);
            }
        });

        jButtonEditSum1.setBackground(new java.awt.Color(51, 51, 51));
        jButtonEditSum1.setText("Print Invoices");
        jButtonEditSum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditSum1ActionPerformed(evt);
            }
        });

        jButtonEditSum2.setBackground(new java.awt.Color(51, 51, 51));
        jButtonEditSum2.setText("Print Summary");
        jButtonEditSum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditSum2ActionPerformed(evt);
            }
        });

        jButtonEditSum3.setBackground(new java.awt.Color(51, 51, 51));
        jButtonEditSum3.setText("Print Day");
        jButtonEditSum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditSum3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonViemInvoices)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAddCr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCash)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonReturn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEditSum2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEditSum1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEditSum))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAddWS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCloseWS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAddSum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonEditSum3)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddWS, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCloseWS, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddSum, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditSum3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditSum, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditSum1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditSum2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonViemInvoices)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonAddCr, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonCash, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonAddCr, jButtonAddSum, jButtonEditSum, jButtonEditSum1, jButtonEditSum2, jButtonEditSum3, jButtonViemInvoices});

    }// </editor-fold>//GEN-END:initComponents

    private void jButtonViemInvoicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViemInvoicesActionPerformed
        if (isOneRecordSelected(jTableSumm, false)) {
            Global.addPanel(InvoicesPanel.class, mainPanel, jTableSumm.getValueAt(jTableSumm.getSelectedRow(), 1));
        }
    }//GEN-LAST:event_jButtonViemInvoicesActionPerformed

    private void jButtonEditSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditSumActionPerformed
        if (isOneRecordSelected(jTableSumm, false)) {
            Summary summary = (Summary) jTableSumm.getValueAt(jTableSumm.getSelectedRow(), 1);
            WorkingSchedule ws = (WorkingSchedule) jTableDays.getValueAt(jTableDays.getSelectedRow(), 0);
            summary.setStatus(Status.LOCKED.getValue());
            Global.CONTROLLER.updateRecord(summary, "Summary");
            addSummDataToTable(ws);
        }
    }//GEN-LAST:event_jButtonEditSumActionPerformed

    private void jButtonAddCrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCrActionPerformed
        if (isOneRecordSelected(jTableSumm, false)) {
            Summary summary = (Summary) jTableSumm.getValueAt(jTableSumm.getSelectedRow(), 1);
            AddCrDialog crDialog = new AddCrDialog(Global.getMainFrame(), true, summary);
            crDialog.setVisible(true);
            addWSDataToTable();
        }
    }//GEN-LAST:event_jButtonAddCrActionPerformed

    private void jButtonAddWSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddWSActionPerformed
        AddDayDialog d = new AddDayDialog(Global.getMainFrame(), true);
        d.setVisible(true);
        WorkingSchedule ws = d.getWorkingSchedule();
        if (null != ws) {
            Global.CONTROLLER.insertRecord(ws, "WorkingSchedule");
            addWSDataToTable();
        }

    }//GEN-LAST:event_jButtonAddWSActionPerformed

    private void jButtonCloseWSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseWSActionPerformed
        if (isOneRecordSelected(jTableDays, true)) {
            int row = jTableDays.getSelectedRow();
            WorkingSchedule ws = (WorkingSchedule) jTableDays.getValueAt(row, 0);
            if (ws.getStatus() != Status.CLOSED.getValue() && ws.areSummariesLocked()) {
                ws.setStatus(Status.CLOSED.getValue());
                Global.CONTROLLER.updateRecord(ws, "WorkingSchedule");
                addWSDataToTable();
            } else {
                JOptionPane.showMessageDialog(this, "Please lock All summaries first");
            }

        }
    }//GEN-LAST:event_jButtonCloseWSActionPerformed

    private void jButtonAddSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddSumActionPerformed
        if (isOneRecordSelected(jTableDays, true)) {
            int row = jTableDays.getSelectedRow();
            WorkingSchedule ws = (WorkingSchedule) jTableDays.getValueAt(row, 0);
            if (ws.getStatus() != Status.CLOSED.getValue()) {
                AddSummaryDialog s = new AddSummaryDialog(Global.getMainFrame(), true);
                s.setVisible(true);
                Summary summary = s.getSummary();
                if (null != summary) {
                    summary.setWSchedule(ws);
                    ws.getSummaryList().add(summary);
                    Global.CONTROLLER.updateRecord(ws, "WorkingSchedule");
                    addWSDataToTable();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Day Closed, You Can not create any more Summaries");
            }

        }
    }//GEN-LAST:event_jButtonAddSumActionPerformed

    private void jTableDaysMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDaysMouseClicked
        if (isOneRecordSelected(jTableDays, true)) {
            addSummDataToTable((WorkingSchedule) jTableDays.getValueAt(jTableDays.getSelectedRow(), 0));
        }
    }//GEN-LAST:event_jTableDaysMouseClicked

    private void jTableSummMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSummMouseClicked
        if (evt.getClickCount() == 2 && isOneRecordSelected(jTableSumm, false)) {
            Global.addPanel(InvoicesPanel.class, mainPanel, jTableSumm.getValueAt(jTableSumm.getSelectedRow(), 1));
        }
    }//GEN-LAST:event_jTableSummMouseClicked

    private void jButtonCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCashActionPerformed
        if (isOneRecordSelected(jTableSumm, false)) {
            Summary summary = (Summary) jTableSumm.getValueAt(jTableSumm.getSelectedRow(), 1);
            AddCashDialog cashDialog = new AddCashDialog(Global.getMainFrame(), true, summary);
            cashDialog.setVisible(true);
            addWSDataToTable();
        }
    }//GEN-LAST:event_jButtonCashActionPerformed

    private void jButtonReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReturnActionPerformed
        if (isOneRecordSelected(jTableDays, true)) {
            System.out.println("--" + (WorkingSchedule) jTableDays.getValueAt(jTableDays.getSelectedRow(), 0));

            Global.addPanel(AddReturnPanel.class, mainPanel, (WorkingSchedule) jTableDays.getValueAt(jTableDays.getSelectedRow(), 0));
        }
    }//GEN-LAST:event_jButtonReturnActionPerformed

    private void jButtonEditSum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditSum1ActionPerformed

        if (isOneRecordSelected(jTableSumm, false)) {
            Summary summary = (Summary) jTableSumm.getValueAt(jTableSumm.getSelectedRow(), 1);
            ReportController.createPurchaseInvoice(summary);

        }
    }//GEN-LAST:event_jButtonEditSum1ActionPerformed

    private void jButtonEditSum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditSum2ActionPerformed
        if (isOneRecordSelected(jTableSumm, false)) {
            Summary summary = (Summary) jTableSumm.getValueAt(jTableSumm.getSelectedRow(), 1);
            ReportController.createSummaryReport(summary);

        }
    }//GEN-LAST:event_jButtonEditSum2ActionPerformed

    private void jButtonEditSum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditSum3ActionPerformed
        if (isOneRecordSelected(jTableDays, true)) {
            int row = jTableDays.getSelectedRow();
            WorkingSchedule ws = (WorkingSchedule) jTableDays.getValueAt(row, 0);
            ArrayList<WorkingSchedule> liWs = new ArrayList<>();
            liWs.add(ws);
            ReportController.createDateWiseSummaryReport(liWs);
        }
    }//GEN-LAST:event_jButtonEditSum3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddCr;
    private javax.swing.JButton jButtonAddSum;
    private javax.swing.JButton jButtonAddWS;
    private javax.swing.JButton jButtonCash;
    private javax.swing.JButton jButtonCloseWS;
    private javax.swing.JButton jButtonEditSum;
    private javax.swing.JButton jButtonEditSum1;
    private javax.swing.JButton jButtonEditSum2;
    private javax.swing.JButton jButtonEditSum3;
    private javax.swing.JButton jButtonReturn;
    private javax.swing.JButton jButtonViemInvoices;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableDays;
    private javax.swing.JTable jTableSumm;
    // End of variables declaration//GEN-END:variables

    private boolean isOneRecordSelected(JTable table, boolean flag) {
        if (table.getSelectedRowCount() > 0 && table.getSelectedRowCount() < 2) {
            return true;
        } else if (flag) {
            JOptionPane.showMessageDialog(this, "Please select One Working Schedule");
            return false;
        } else {
            JOptionPane.showMessageDialog(this, "Please select One Summary");
            return false;
        }
    }

    private void addWSDataToTable() {
        dtmDays = (DefaultTableModel) jTableDays.getModel();
        dtmSumm = (DefaultTableModel) jTableSumm.getModel();
        dtmDays.setRowCount(0);

        ArrayList<WorkingSchedule> list = (ArrayList<WorkingSchedule>) Global.CONTROLLER.fetch("WorkingSchedule").getResponseObject();

        for (WorkingSchedule w : list) {
            dtmDays.addRow(new Object[]{
                w,
                Global.DATE_UTIL.getDayOfWeek(w.getDate()),
                Status.get(w.getStatus())
            });
        }
        if (!list.isEmpty()) {
            jTableDays.setRowSelectionInterval(0, 0);
            addSummDataToTable((WorkingSchedule) jTableDays.getValueAt(jTableDays.getSelectedRow(), 0));
        }
    }

    private void addSummDataToTable(WorkingSchedule ws) {
        dtmSumm.setRowCount(0);
        for (Summary s : ws.getSummaryList()) {
            dtmSumm.addRow(new Object[]{
                Global.DATE_UTIL.getStingDateFromLongValue(ws.getDate()),
                s,
                s.getSummaryBooker(),
                s.getSummaryRoute(),
                s.getAmount(),
                s.getCash(),
                s.getCredit(),
                s.getBalance(),
                Status.get(s.getStatus())
            });
        }
    }

}
