/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ar.ais.views.panels.data;

import com.ar.ais.enums.Status;
import com.ar.ais.models.EntityBeans.Booker;
import com.ar.ais.models.EntityBeans.Route;
import com.ar.ais.models.EntityBeans.Shop;
import com.ar.ais.models.Response;
import com.ar.ais.utililty.Frmttr;
import com.ar.ais.utililty.Global;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Adeel rana
 */
public class AddShopPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddExpensePanel
     */
    JPanel mainPanel;

    public AddShopPanel(JPanel mainPanel) {
        initComponents();
        this.initData();
        this.mainPanel = mainPanel;
    }

    public AddShopPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupType = new javax.swing.ButtonGroup();
        buttonGroupFormat = new javax.swing.ButtonGroup();
        star4 = new javax.swing.JLabel();
        star3 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        valid4 = new javax.swing.JLabel();
        valid3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        valid1 = new javax.swing.JLabel();
        jTextName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextAddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextOpenCr = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jComboBoxBooker = new javax.swing.JComboBox<>();
        jComboBoxRoute = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jRadioJoined = new javax.swing.JRadioButton();
        jRadioBooker = new javax.swing.JRadioButton();
        jRadioAgency = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRadioPercentage = new javax.swing.JRadioButton();
        jRadioRs = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jTextDiscount = new javax.swing.JTextField();
        jLabelDiscount2 = new javax.swing.JLabel();
        jTextDiscount2 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(51, 51, 51));

        star4.setForeground(new java.awt.Color(255, 0, 0));
        star4.setText("  ");

        star3.setForeground(new java.awt.Color(255, 0, 0));
        star3.setText("  ");

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAdd.setText("SAVE");
        btnAdd.setNextFocusableComponent(jComboBoxBooker);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        valid4.setForeground(new java.awt.Color(255, 0, 0));
        valid4.setText("  ");

        valid3.setForeground(new java.awt.Color(255, 0, 0));
        valid3.setText("  ");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Route");

        valid1.setForeground(new java.awt.Color(255, 0, 0));
        valid1.setText(" ");

        jTextName.setNextFocusableComponent(jTextAddress);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Shop");

        jTextAddress.setNextFocusableComponent(jTextOpenCr);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Opening Cr");

        jTextOpenCr.setNextFocusableComponent(jRadioAgency);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Booker");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Address");

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Name");

        jComboBoxBooker.setNextFocusableComponent(jComboBoxRoute);
        jComboBoxBooker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBookerActionPerformed(evt);
            }
        });

        jComboBoxRoute.setNextFocusableComponent(jTextName);
        jComboBoxRoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRouteActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Discount");

        jRadioJoined.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroupType.add(jRadioJoined);
        jRadioJoined.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jRadioJoined.setForeground(new java.awt.Color(255, 255, 255));
        jRadioJoined.setText("Joined");
        jRadioJoined.setActionCommand("JOIN");
        jRadioJoined.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioJoinedItemStateChanged(evt);
            }
        });

        jRadioBooker.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroupType.add(jRadioBooker);
        jRadioBooker.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jRadioBooker.setForeground(new java.awt.Color(255, 255, 255));
        jRadioBooker.setText("Booker");
        jRadioBooker.setActionCommand("DBT");

        jRadioAgency.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroupType.add(jRadioAgency);
        jRadioAgency.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jRadioAgency.setForeground(new java.awt.Color(255, 255, 255));
        jRadioAgency.setSelected(true);
        jRadioAgency.setText("Agency");
        jRadioAgency.setActionCommand("AG");
        jRadioAgency.setNextFocusableComponent(jRadioPercentage);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Type");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Format");

        jRadioPercentage.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroupFormat.add(jRadioPercentage);
        jRadioPercentage.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jRadioPercentage.setForeground(new java.awt.Color(255, 255, 255));
        jRadioPercentage.setSelected(true);
        jRadioPercentage.setText("Percentage");
        jRadioPercentage.setActionCommand("PER");
        jRadioPercentage.setNextFocusableComponent(jTextDiscount);

        jRadioRs.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroupFormat.add(jRadioRs);
        jRadioRs.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jRadioRs.setForeground(new java.awt.Color(255, 255, 255));
        jRadioRs.setText("Rs");
        jRadioRs.setActionCommand("RS");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Value");

        jTextDiscount.setNextFocusableComponent(jTextDiscount2);

        jLabelDiscount2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelDiscount2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDiscount2.setText("Value");

        jTextDiscount2.setNextFocusableComponent(btnAdd);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(12, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxBooker, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(star3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(star4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(valid1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboBoxRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(valid3)
                                        .addComponent(valid4)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(36, 36, 36)
                                    .addComponent(jTextOpenCr, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelDiscount2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextDiscount2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jRadioAgency)
                                            .addGap(18, 18, 18)
                                            .addComponent(jRadioBooker)
                                            .addGap(18, 18, 18)
                                            .addComponent(jRadioJoined))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jRadioPercentage)
                                            .addGap(18, 18, 18)
                                            .addComponent(jRadioRs))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jComboBoxBooker, jComboBoxRoute, jTextAddress, jTextName, jTextOpenCr});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valid1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel5)
                        .addComponent(jComboBoxBooker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxRoute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextOpenCr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(jLabel17))
                            .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioJoined)
                    .addComponent(jRadioBooker)
                    .addComponent(jRadioAgency)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(star3)
                            .addComponent(valid3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(star4)
                            .addComponent(valid4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jRadioPercentage)
                            .addComponent(jRadioRs))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDiscount2)
                    .addComponent(jTextDiscount2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAdd, jComboBoxBooker, jComboBoxRoute, jLabel16, jLabel5, jLabel7, jLabel9, jTextAddress, jTextDiscount, jTextDiscount2, jTextName, jTextOpenCr});

    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        addShop();
        Global.addPanel(ShopsPanel.class, mainPanel);
    }//GEN-LAST:event_btnAddActionPerformed

    private void jComboBoxRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRouteActionPerformed
    }//GEN-LAST:event_jComboBoxRouteActionPerformed

    private void jComboBoxBookerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBookerActionPerformed
        Booker booker = (Booker) jComboBoxBooker.getSelectedItem();
        if (null != booker) {
            Global.addListToCombo(jComboBoxRoute, booker.getRouteList());
        }
    }//GEN-LAST:event_jComboBoxBookerActionPerformed

    private void jRadioJoinedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioJoinedItemStateChanged
        if (jRadioJoined.isSelected()) {
            jLabelDiscount2.setVisible(true);
            jTextDiscount2.setVisible(true);
        } else {
            jLabelDiscount2.setVisible(false);
            jTextDiscount2.setVisible(false);
        }
    }//GEN-LAST:event_jRadioJoinedItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.ButtonGroup buttonGroupFormat;
    private javax.swing.ButtonGroup buttonGroupType;
    private javax.swing.JComboBox<String> jComboBoxBooker;
    private javax.swing.JComboBox<String> jComboBoxRoute;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDiscount2;
    private javax.swing.JRadioButton jRadioAgency;
    private javax.swing.JRadioButton jRadioBooker;
    private javax.swing.JRadioButton jRadioJoined;
    private javax.swing.JRadioButton jRadioPercentage;
    private javax.swing.JRadioButton jRadioRs;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextAddress;
    private javax.swing.JTextField jTextDiscount;
    private javax.swing.JTextField jTextDiscount2;
    private javax.swing.JTextField jTextName;
    private javax.swing.JTextField jTextOpenCr;
    private javax.swing.JLabel star3;
    private javax.swing.JLabel star4;
    private javax.swing.JLabel valid1;
    private javax.swing.JLabel valid3;
    private javax.swing.JLabel valid4;
    // End of variables declaration//GEN-END:variables

    private void initData() {
        jLabelDiscount2.setVisible(false);
        jTextDiscount2.setVisible(false);
        Global.addListToCombo(jComboBoxBooker, (List) Global.CONTROLLER.fetchActive("Booker").getResponseObject());
    }

    private void addShop() {
        Shop s = new Shop();

        Booker booker = (Booker) jComboBoxBooker.getSelectedItem();
        Route route = (Route) jComboBoxRoute.getSelectedItem();

        if (null != booker && null != route) {
            s.setShopBooker(booker);
            s.setShopRoute(route);
            s.setName(jTextName.getText());
            s.setAddress(jTextAddress.getText());
            s.setOpeningCr(Frmttr.getDoubleFromString(jTextOpenCr.getText()));
            s.setCurrentCr(s.getOpeningCr());
            s.setOpeningDate(Global.DATE_UTIL.getNewDate().getTime());
            s.setType("");
            s.setStatus(Status.ACTIVE.getValue());

            s.setDiscountType(buttonGroupType.getSelection().getActionCommand() + "_" + buttonGroupFormat.getSelection().getActionCommand());
            s.setDiscountAgency(Frmttr.getDoubleFromString(jTextDiscount.getText()));
            s.setDiscountDistributor(Frmttr.getDoubleFromString(jTextDiscount2.getText()));

            Response insertRecord = Global.CONTROLLER.insertRecord(s, "Shop");

            if (insertRecord.isSuccess()) {
                JOptionPane.showMessageDialog(this, "Record Added Successfully");
            } else {
                JOptionPane.showMessageDialog(this, "error");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Booker OR Route");
        }

    }
}
